CfpUserBundle_biography:
    resource: "@CfpUserBundle/Resources/config/routing/biography.yml"
    prefix:   /biography

CfpUserBundle_widget:
    resource: "@CfpUserBundle/Resources/config/routing/widget.yml"
    prefix:   /widget

CfpUserBundle_user:
    resource: "@CfpUserBundle/Resources/config/routing/user.yml"
    prefix:   /user


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_ajax_checkuser:
    pattern:  /account/ajax/checkuser
    defaults: { _controller: "CfpUserBundle:User:checkUser" }

fos_user_ajax_checkemail:
    pattern:  /account/ajax/checkemail
    defaults: { _controller: "CfpUserBundle:User:checkEmail" }


#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

github_login:
    pattern: /login/check-github
