parameters:
#    cfp_talk.example.class: Cfp\TalkBundle\Example

services:
#    cfp_talk.example:
#        class: %cfp_talk.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
